[tool.poetry]
name = "combinators-dataset"
version = "0.1.0"
description = "Typed Combinators Dataset"
authors = ["Carlos Fernandez <carlos.ferlo@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
tqdm = "^4.67.1"
datasets = "^4.0.0"
huggingface-hub = "^0.34.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
